const actionTypes = {
    liveImagesTypes: {
        GET_LIVE_IMAGE: 'GET_LIVE_IMAGE',
        GET_LIVE_STATISTIC: 'GET_LIVE_STATISTIC',
        LIVE_IMAGE_FAIL: 'LIVE_IMAGE_FAIL',
        START_STOP_LIVE: 'START_STOP_LIVE'
    },
    referenceImagesTypes: {
        COUNT_ACTIVE_REFERENCE_OBJECTS: 'COUNT_ACTIVE_REFERENCE_OBJECTS',
        NUMBER_ACTIVE_REFERENCE_OBJECT: 'NUMBER_ACTIVE_REFERENCE_OBJECT',
        ACTIVE_REFERENCE_OBJECT: 'ACTIVE_REFERENCE_OBJECT',
        REFERENCE_OBJECT: 'REFERENCE_OBJECT',
        SET_ACTIVE_REFERENCE_OBJECT: 'SET_ACTIVE_REFERENCE_OBJECT'
    },
    commonCommandsTypes: {
        SAVE_TO_FLASH: 'SAVE_TO_FLASH',
        GET_CAM_STATUS: 'GET_CAM_STATUS',
        CAM_MODE: 'CAM_MODE',
        AVAILABLE_TOOLS: 'AVAILABLE_TOOLS',
        ROI_SIZE: 'ROI_SIZE',
        OBJECT_MATCH_THRESHOLD: 'OBJECT_MATCH_THRESHOLD',
        PIXEL_COUNTER_INTENSITY_RANGE: 'PIXEL_COUNTER_INTENSITY_RANGE',
        PIXEL_COUNTER_NO_PIXELS_IN_RANGE: 'PIXEL_COUNTER_NO_PIXELS_IN_RANGE',
        EDGE_PIXEL_COUNTER_STRENGTH: 'EDGE_PIXEL_COUNTER_STRENGTH',
        EDGE_PIXEL_COUNTER_NO_PIXELS_IN_RANGE: 'EDGE_PIXEL_COUNTER_NO_PIXELS_IN_RANGE',
        PATTERN_SCORE_THRESHOLD: 'PATTERN_SCORE_THRESHOLD',
    },
    logImagesTypes: {
        LOCK_LOG: 'LOCK_LOG',
        UNLOCK_LOG: 'UNLOCK_LOG',
        LOAD_IMAGE: 'LOAD_IMAGE'
    }
}

export const commandList = {
    liveImagesList: {
        SELECT_REFERENCE_OBJECT: 'sINT_1', //
        GET_NUMBER_ACTIVE_OF_REFERENCE_OBJECT: 'gINT_1', // return int [0, 31]
        GET_COUNT_CONFIGURED_REFERENCE_OBJECTS: 'gINT_2', // return int [0, 31]
    }
}

export default actionTypes